### ISSUE TITLE
base chat_flows move to package

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#281]
![image](https://user-images.githubusercontent.com/6021844/69779551-a9d97480-11a8-11ea-98e7-3b6ca0335e3f.png)

- [x] move test chats to a test package 
- [ ] create some wiki pages underneith

## implementation instructions

```toml
[source]
name = "chatbot_examples"
description = "examples for chatbot"
threebot = "threefold"
version = "1.0.0"

```

move under zerobot in packages on threebot
