### ISSUE TITLE
base.py actor moved to package

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_threebot#283]
![image](https://user-images.githubusercontent.com/6021844/69779489-7d255d00-11a8-11ea-96ec-1538f90dcfef.png)

- [x] move to package as described below
- [x] create some wiki pages underneath

## implementation instructions

```toml
[source]
name = "???"
description = "???"
threebot = "threefold"
version = "1.0.0"

```

move under zerobot in packages on threebot
