### ISSUE TITLE
design issue in the structure of the reservation object

### ISSUE THREAD

**Issue by ahmedelsayed-93** [threefoldtech/jumpscaleX_threebot#32]
As documented [here](https://github.com/threefoldtech/jumpscaleX_threebot/blob/a25176f937f0d158683f46bd5a1d6b7c99e7749a/ThreeBotPackages/threefold/tfgrid_workloads/docs/reservation.md#models)
The ```data``` field in the reservation object is immutable, and this field contains the workloads info which needs to be populated with the workloads ids and reservation id once the reservation object is created and get an id, so the problem is the ```json``` field which is the json representation of the data object can't be generated from the user side (cause the workloads  ids and reservation objects are not set at this moment), so we need to have a another look at the structure of the reservation object

**Comment by zaibon** [comment]
To make it more explicit, here is the details:

https://github.com/threefoldtech/jumpscaleX_threebot/blob/3df353da4f184b8bb32097856941303cd0c1a887/ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_1.toml#L4-L6

These 2 fields of the `tfgrid.reservation.1` schema are supposed to be immutable

`data_reservation` field is of the type:
https://github.com/threefoldtech/jumpscaleX_threebot/blob/3df353da4f184b8bb32097856941303cd0c1a887/ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_1.toml#L22-L35

so it is a list of all the possible workload. Then as an example here is the `tfgrid.reservation.volume.1` schema:
https://github.com/threefoldtech/jumpscaleX_threebot/blob/3df353da4f184b8bb32097856941303cd0c1a887/ThreeBotPackages/threefold/tfgrid_workloads/models/tfgrid_reservation_volume_1.toml#L3-L13

Here we see the workload_id field which is supposed to be an ID given by BCDB itself when this object is saved.

So the problems is, if the all `data_reservation` field needs to be immutable cause it is the what is used to sign the reservation. Then it is impossible that it contains a `workload_id` field that is supposed to be populated by BCDB at save time.

**Comment by zaibon** [comment]
To me the obvious way to solve this is to avoid having a list of different workload in a same reservation.
So I would replace the current `tfgrid.reservation.data.1` to something like
```toml
@url = tfgrid.reservation.data.1
#this one does not change over time
description = ""
#need to get to consensus
signing_request_provision = (O) !tfgrid.reservation.signing.request.1
signing_request_delete = (O) !tfgrid.reservation.signing.request.1
node_id = (I)
workload_type = "volume,zdb,container,network" (E)
# byte encoded version of the actual workload definition
workload_detail = (B) 
expiration_provisioning = (T)
expiration_reservation = (T)
```

Then we can remove all the `workload_id` and `nodeid` field from 
- tfgrid.reservation.container.1
- tfgrid.reservation.volume.1
- tfgrid.reservation.network.1
- tfgrid.reservation.zdb.1
